# Generated by Django 5.1.4 on 2024-12-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalAssistance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='Budget',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EducationalAssistance.batch'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
