# Generated by Django 5.1.4 on 2024-12-10 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalAssistance', '0002_remove_batch_budget_student_address_student_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EducationalAssistance.batch'),
        ),
    ]
