# Generated by Django 5.1.4 on 2024-12-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalAssistance', '0004_alter_batch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='current_count',
            field=models.IntegerField(default=0),
        ),
    ]
