# Generated by Django 5.1.4 on 2024-12-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EducationalAssistance', '0008_student_datesubmitted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('batch', 'email'), name='Unique email per Batch'),
        ),
    ]
